In [ ]:
scores = [78,69,65]   # 原始分數
new_scores=[]

for score in scores:
    new_scores.append(score + 3)    # 原始分數各加3分

new_scores

[81, 72, 68]

In [ ]:
# list comprehention(快速建立list)
scores = [78,69,65]
new_scores = [score + 3 for score in scores]   #必需使用for in迴圈 
new_scores

[81, 72, 68]

In [3]:
scores = [78,69,65]
scores * 2

[78, 69, 65, 78, 69, 65]

In [4]:
[67,92,85] + [78,69,65]

[67, 92, 85, 78, 69, 65]

In [12]:
import numpy as np

scores = np.array([78, 69, 65])
print(type(scores))
new_scores = scores + 3

<class 'numpy.ndarray'>


In [ ]:
#常用的統計指標
print(scores.sum())   #總和
print(scores.mean())  #平均數
print(scores.std())   #標準差
print(scores.min())   #最小值
print(scores.max())   #最大值
np.median(scores)     #中位數

212
70.66666666666667
5.436502143433363
65
78


np.float64(69.0)

In [17]:
students = np.array([
    [67,94,65],
    [78,92,68],
    [59,92,87]
    ])
students

array([[67, 94, 65],
       [78, 92, 68],
       [59, 92, 87]])

In [ ]:
# 常用的查詢屬性: 維度，元素數量，形狀(列數，欄數)
students.ndim, students.size, students.shape

(2, 9, (3, 3))

In [ ]:
#第1位學生第1科的分數
students[0,0]

np.int64(67)

In [33]:
#第1位學生的分數加3分
students[0,:] + 3 

array([70, 97, 68])

In [24]:
#前2位學生的分數
students[0:2,:]

array([[67, 94, 65],
       [78, 92, 68]])

In [29]:
#倒數2位學生的分數
students[-2:,:]

array([[78, 92, 68],
       [59, 92, 87]])

In [ ]:
#第1科(國文)分數
students[:,0]

array([67, 78, 59])

In [ ]:
#前2科(國文，英文)分數
students[:,0:2]

array([[67, 94],
       [78, 92],
       [59, 92]])

In [35]:
students[0,0] = 100
students

array([[100,  94,  65],
       [ 78,  92,  68],
       [ 59,  92,  87]])

In [36]:
students[0,0] -= 10
students

array([[90, 94, 65],
       [78, 92, 68],
       [59, 92, 87]])